init:
  # SoureLink requires the files to have the same checksum.
  # Make sure git doesn't mess with line endings.
  - git config --global core.autocrlf false

environment:
  global:
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    DOTNET_CLI_TELEMETRY_OPTOUT: 1

os: Visual Studio 2017

install:
  - cmd: git fetch --depth 50
  - cmd: git fetch --tags --depth 50
  - cmd: git fetch origin master:master --depth 50
  - cmd: bash ./script/prepare-appveyor.sh
  # Display .NET Core info
  - cmd: dotnet --info
  # Restore build script
  - cmd: dotnet restore build

before_build:
  - cmd: bash ./script/git-version.sh --verbose get

build_script:
  - cmd: dotnet build build

test_script:
  - cmd: dotnet test --no-build --logger "trx;LogFileName=testresult.xml" test/Sample.Test/Sample.Test.fsproj
  - ps: (New-Object 'System.Net.WebClient').UploadFile("https://ci.appveyor.com/api/testresults/mstest/$($env:APPVEYOR_JOB_ID)", (Resolve-Path test/Sample.Test/TestResults/testresult.xml))

artifacts:
  - path: artifacts/*.nupkg

deploy:
  - provider: Environment
    name: YoloDev MyGet
    on:
      branch: master

  - provider: Environment
    name: NuGet Central
    on:
      appveyor_repo_tag: true