language: csharp
sudo: required
dist: trusty
mono: none

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1

addons:
  apt:
    packages:
      - libunwind8

os:
  - linux
  - osx

osx_image: xcode8.2

before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
  - bash ./script/prepare-travis.sh
  - bash ./script/git-version.sh --verbose get

install:
  - dotnet restore build

script:
  - dotnet build build /v:n